### ISSUE TITLE
some problem about the code

### ISSUE THREAD

**Issue by angryBird2014** [dillonalaird/Attention#1]
I read the paper "Effective Approaches to Attention-based Neural Machine Translation",but I'm interested in the"local attention(local p)",can you tell me how to implement it with kears or tensorflow?

**Comment by dillonalaird** [comment]
Unfortunately, I don't have time to implement it right now but it looks like there's a feature request for it in Tensorflow https://github.com/tensorflow/tensorflow/issues/10842 You might also try looking at the source code for attention_wrapper https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py
